"""create core schema: opponents clubs tournaments matches sets

Revision ID: c2f5aaa3b9d7
Revises: 92c446b515d8
Create Date: 2026-07-14 15:04:01.458497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2f5aaa3b9d7'
down_revision: Union[str, Sequence[str], None] = '92c446b515d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('surface', sa.Enum('Hard', 'Clay', 'Grass', 'Carpet', name='surface'), nullable=True),
    sa.Column('environment', sa.Enum('Indoor', 'Outdoor', name='environment'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False)
    op.create_table('opponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('handedness', sa.Enum('R', 'L', name='handedness'), nullable=True),
    sa.Column('age_range', sa.Enum('Under 18', '18-29', '30-39', '40-49', '50-59', '60+', name='age_range'), nullable=True),
    sa.Column('level', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opponents_last_name'), 'opponents', ['last_name'], unique=False)
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('season', sa.String(length=40), nullable=True),
    sa.Column('tournament_type', sa.Enum('Knockout Tournament', 'Ranking League', name='tournament_type'), nullable=False),
    sa.Column('format', sa.String(length=80), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_club_id'), 'tournaments', ['club_id'], unique=False)
    op.create_index(op.f('ix_tournaments_name'), 'tournaments', ['name'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('surface', sa.Enum('Hard', 'Clay', 'Grass', 'Carpet', name='surface'), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('played', 'scheduled', name='match_status'), server_default='played', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opponent_id'], ['opponents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_club_id'), 'matches', ['club_id'], unique=False)
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_index(op.f('ix_matches_opponent_id'), 'matches', ['opponent_id'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('set_no', sa.Integer(), nullable=False),
    sa.Column('games_won', sa.Integer(), nullable=False),
    sa.Column('games_lost', sa.Integer(), nullable=False),
    sa.Column('tiebreak', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'set_no', name='uq_sets_match_id_set_no')
    )
    op.create_index(op.f('ix_sets_match_id'), 'sets', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sets_match_id'), table_name='sets')
    op.drop_table('sets')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_opponent_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_club_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_tournaments_name'), table_name='tournaments')
    op.drop_index(op.f('ix_tournaments_club_id'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_index(op.f('ix_opponents_last_name'), table_name='opponents')
    op.drop_table('opponents')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_table('clubs')
    # Drop the enum types the tables above depended on so the chain returns to
    # a truly empty database (autogenerate omits these on Postgres).
    sa.Enum(name='match_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='tournament_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='environment').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='surface').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='age_range').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='handedness').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
