/**
 * Web-only wiring for the shared `@tennisfolio/core` icon encoding: maps each
 * curated lucide icon name to its component, and each color token to the
 * Tailwind utility classes that consume the `--rg-*`-derived semantic tokens
 * in index.css. Never hard-code hex here — always go through a token class.
 */
import {
  Award,
  Building2,
  CloudSun,
  Compass,
  Crown,
  Dumbbell,
  Flag,
  Flame,
  Gauge,
  Globe,
  Home,
  Landmark,
  type LucideIcon,
  MapPin,
  Medal,
  Mountain,
  Palmtree,
  Rocket,
  Shield,
  Snowflake,
  Sparkles,
  Star,
  Sun,
  Swords,
  Target,
  TreePine,
  Trophy,
  Umbrella,
  Users,
  Waves,
  Zap,
} from 'lucide-react'

import type { EntityIconColorToken, EntityIconName } from '@tennisfolio/core'
import { ENTITY_ICON_COLOR_TOKENS, ENTITY_ICON_NAMES } from '@tennisfolio/core'

export const ENTITY_ICON_COMPONENTS: Record<EntityIconName, LucideIcon> = {
  trophy: Trophy,
  award: Award,
  medal: Medal,
  star: Star,
  crown: Crown,
  flag: Flag,
  target: Target,
  swords: Swords,
  dumbbell: Dumbbell,
  gauge: Gauge,
  'map-pin': MapPin,
  'building-2': Building2,
  landmark: Landmark,
  home: Home,
  globe: Globe,
  compass: Compass,
  mountain: Mountain,
  'tree-pine': TreePine,
  waves: Waves,
  palmtree: Palmtree,
  sun: Sun,
  'cloud-sun': CloudSun,
  umbrella: Umbrella,
  snowflake: Snowflake,
  zap: Zap,
  flame: Flame,
  shield: Shield,
  rocket: Rocket,
  sparkles: Sparkles,
  users: Users,
}

/** Human-readable labels for the icon picker grid. */
export const ENTITY_ICON_LABELS: Record<EntityIconName, string> = {
  trophy: 'Trophy',
  award: 'Award',
  medal: 'Medal',
  star: 'Star',
  crown: 'Crown',
  flag: 'Flag',
  target: 'Target',
  swords: 'Swords',
  dumbbell: 'Dumbbell',
  gauge: 'Gauge',
  'map-pin': 'Map pin',
  'building-2': 'Building',
  landmark: 'Landmark',
  home: 'Home',
  globe: 'Globe',
  compass: 'Compass',
  mountain: 'Mountain',
  'tree-pine': 'Pine tree',
  waves: 'Waves',
  palmtree: 'Palm tree',
  sun: 'Sun',
  'cloud-sun': 'Partly cloudy',
  umbrella: 'Umbrella',
  snowflake: 'Snowflake',
  zap: 'Lightning',
  flame: 'Flame',
  shield: 'Shield',
  rocket: 'Rocket',
  sparkles: 'Sparkles',
  users: 'Users',
}

/** Curated emoji set offered by the picker's emoji tab. */
export const ENTITY_ICON_EMOJIS: readonly string[] = [
  '🎾',
  '🏆',
  '🥇',
  '🥈',
  '🥉',
  '🏅',
  '⭐',
  '🌟',
  '🔥',
  '⚡',
  '🎯',
  '🥎',
  '🏟️',
  '🏸',
  '🚩',
  '📍',
  '🏠',
  '🌍',
  '☀️',
  '🌤️',
  '☂️',
  '❄️',
  '🏔️',
  '🌊',
  '🌴',
  '🛡️',
  '🚀',
  '✨',
  '👥',
  '⚔️',
]

export const ENTITY_ICON_COLOR_CLASSES: Record<EntityIconColorToken, string> = {
  primary: 'text-primary',
  secondary: 'text-secondary',
  win: 'text-win',
  loss: 'text-loss',
  highlight: 'text-highlight',
  destructive: 'text-destructive',
  'muted-foreground': 'text-muted-foreground',
}

export const ENTITY_ICON_COLOR_SWATCH_CLASSES: Record<EntityIconColorToken, string> = {
  primary: 'bg-primary',
  secondary: 'bg-secondary',
  win: 'bg-win',
  loss: 'bg-loss',
  highlight: 'bg-highlight',
  destructive: 'bg-destructive',
  'muted-foreground': 'bg-muted-foreground',
}

export const ENTITY_ICON_COLOR_LABELS: Record<EntityIconColorToken, string> = {
  primary: 'Primary',
  secondary: 'Secondary',
  win: 'Win',
  loss: 'Loss',
  highlight: 'Highlight',
  destructive: 'Destructive',
  'muted-foreground': 'Muted',
}

export { ENTITY_ICON_COLOR_TOKENS, ENTITY_ICON_NAMES }
